<?php
namespace app\index\controller;

use app\index\model\User as UserModel;

class User extends Base
{
    private $userModel;
    protected $middleware = [
        'Check' => ['only'=> ['middle'] ],
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->userModel = new UserModel();
    }


    public function index()
    {
        return 'user index';
    }

    //http://localhost/tplearn/public/index/user/hello
    public function hello($name = 'ThinkPHP5')
    {
        return 'user hello,' . $name;
    }

   //http://localhost/tplearn/public/index/user/jsonreturn
   public function jsonreturn()
   {
        return json(['status' => 600001, 'info' => 'Open chain failed to open chain failed', 'chn_info' => '开链失败']);
   }

     //http://localhost/tplearn/public/index/user/getparam?text=12aa&shortName=btc&bonus=12&fat=8.23
     //http://localhost/tplearn/public/index/user/getparam?shortName=btc&bonus=12&fat=8.23
     public function getparam()
     {
        $text = $this->request->param('text');
        $shortName = $this->request->param('shortName', 'ETH');
        $bonus = $this->request->param('bonus', 0, 'intval');
        $fat = $this->request->param('fat', 0, 'floatval');

        return json(['text' => $text, 
        'shortName' => $shortName, 
        'bonus' => $bonus,
        'fat' => $fat,
        ]);
     }

     //http://localhost/tplearn/public/index/user/middle?token=aaa
     //http://localhost/tplearn/public/index/user/middle
     public function middle()
     {
        $userInfo = session('userInfo');
        return json($userInfo);
     }

     //http://localhost/tplearn/public/index/user/getsqldata
     public function getsqldata()
     {
        $data = $this->userModel->gettest1(1001);
        return json($data);
     }


     
}
